name: yourinrolltoolsstream
description: Camera control on Android and iOS. record video, take pictures, and also support rtmp streaming. Based on the camera plugin for the Youinroll Flutter social network community.
version: 1.1.1
homepage: https://github.com/Xatiko540/yourinrolltoolsstream

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=3.0.5"

dependencies:
  flutter:
    sdk: flutter
  rename: ^2.0.1

dev_dependencies:
  path_provider: ^2.0.5
  video_player: ^2.2.5
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  pedantic: ^1.8.0+1

# The following section is specific to Flutter.
flutter:
  plugin:
    platforms:
      android:
        package: com.app.rtmp_publisher
        pluginClass: YourinrolltoolsstreamPlugin
      ios:
        pluginClass: YourinrolltoolsstreamPlugin
